language: node_js

services:
  - docker

node_js:
  - 12

cache:
  directories:
    - node_modules

before_script:
  - yarn
  - yarn docker:mongodb:create

script:
  - yarn test:cov

after_success:
  - bash <(curl -s https://codecov.io/bash)